#!/usr/bin/env python

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# (C) Copyright 2008 Kulbir Saini <kulbirsaini@students.iiit.ac.in>
#
# For more information check http://cachevideos.com/
#

import logging
import logging.handlers
import os
import pwd
import shutil
import sys

# The user which runs the squid proxy server or daemon.
squid_user = 'squid'
# The group which runs the squid proxy server or daemon.
squid_group = 'squid'
# The location of squid configuration directory.
squid_conf_dir = '/etc/squid/'
# The location of directory where squid logs are stored.
squid_log_dir = '/var/log/squid'
# The directory to store application specific configuration files for Apache Web Server.
apache_conf_dir = '/etc/httpd/conf.d/'
# The directory to store man pages.
man_dir = '/usr/share/man/man8/'

# Try to locate the youtube_cache directory containing python files.
if os.path.isdir(os.path.join(squid_conf_dir, 'youtube_cache')):
    sys.path = ['/etc/squid/youtube_cache/'] + sys.path
    from config import readMainConfig, readStartupConfig
else:
    error(USAGE_ERROR)

# The location of system configuration file for youtube cache.
config_file = '/etc/youtube_cache.conf'
# The location of logfile to write setup/install logs.
setup_logfile = '/var/log/squid/youtube_cache.log'
# Read the configure file.
mainconf =  readMainConfig(readStartupConfig(config_file, '/'))

# Gloabl Options
base_dir = mainconf.base_dir
temp_dir = os.path.join(base_dir, mainconf.temp_dir)
logfile = mainconf.logfile
format = '%s'

USAGE_ERROR = 1
UID_ERROR = 2
UPDATE_ERROR = 3

# Youtube specific options
youtube_cache_dir = os.path.join(base_dir, mainconf.youtube_cache_dir)

# Metacafe specific options
metacafe_cache_dir = os.path.join(base_dir, mainconf.metacafe_cache_dir)

# Dailymotion specific options
dailymotion_cache_dir = os.path.join(base_dir, mainconf.dailymotion_cache_dir)

# Google.com specific options
google_cache_dir = os.path.join(base_dir, mainconf.google_cache_dir)

# Redtube.com specific options
redtube_cache_dir = os.path.join(base_dir, mainconf.redtube_cache_dir)

# Xtube.com specific options
xtube_cache_dir = os.path.join(base_dir, mainconf.xtube_cache_dir)

# Vimeo.com specific options
vimeo_cache_dir = os.path.join(base_dir, mainconf.vimeo_cache_dir)

# Wrzuta.pl specific options
wrzuta_cache_dir = os.path.join(base_dir, mainconf.wrzuta_cache_dir)

# Wrzuta.pl specific options
youporn_cache_dir = os.path.join(base_dir, mainconf.youporn_cache_dir)

# List of cache directories
squid_cache_dir_list = [base_dir, temp_dir, youtube_cache_dir, metacafe_cache_dir, dailymotion_cache_dir, google_cache_dir, redtube_cache_dir, xtube_cache_dir, vimeo_cache_dir, wrzuta_cache_dir, youporn_cache_dir]

def set_logging():
    logging.basicConfig(level=logging.DEBUG,
                        format='%(asctime)s %(levelname)s %(message)s',
                        filename=setup_logfile,
                        filemode='a')
    return logging.info

def create_dir(dir, user=None, group=None, mode=0755):
    """Create a directory in the filesystem with user:group ownership and mode as permissions."""
    try:
        os.makedirs(dir, mode)
        log(format%("Created directory " + dir + " ."))
    except:
        log(format%("Could not create directory " + dir + " ."))
        return False

    return dir_perms_and_ownership(dir, user, group, mode)

def dir_perms_and_ownership(dir, user=None, group=None, mode=0755):
    """Change the permissions and ownership of a directory."""
    try:
        os.chmod(dir, mode)
    except:
        log(format%("Could not change permissions of directory " + dir + " ."))

    if user == None:
        return True

    user = pwd.getpwnam(user)[2]
    if group != None:
        group = pwd.getpwnam(group)[3]
    else:
        group = user

    try:
        os.chown(dir, user, group)
        log(format%("Changed ownership of " + dir + " ."))
    except:
        log(format%("Could not change ownership of directory " + dir + " ."))
        return False

    return True

def create_file(filename, user=None, group=None, mode=0755):
    """Create a file in the filesystem with user:group ownership and mode as permissions."""
    try:
        file = open(filename, 'a')
        file.close()
        log(format%("Created file " + filename + " ."))
    except:
        log(format%("Could not create file " + filename + " ."))
        return False
    
    try:
        os.chmod(filename, mode)
        log(format%("Changed mode of file " + filename + " ."))
    except:
        log(format%("Could not change the mode of the file " + filename + " ."))
        return False

    if user == None:
        return True

    user = pwd.getpwnam(user)[2]
    if group != None:
        group = pwd.getpwnam(group)[3]
    else:
        group = user

    try:
        os.chown(filename, user, group)
        log(format%("Changed ownership of file " + filename + " ."))
    except:
        log(format%("Could not change ownership of file " + filename + " ."))
        return False
    return True

def copy_file(source, dest):
    """Copies the source file to dest file."""
    try:
        shutil.copy2(source, dest)
        log(format%("Copied file " + source + " to " + dest + " ."))
    except:
        log(format%("Could not copy the file " + source + " to file " + dest + " ."))
        return False
    return True

def copy_dir(source, dest):
    """Copies the source directory recursively to dest dir."""
    try:
        if os.path.isdir(dest):
            shutil.rmtree(dest)
            log(format%("Removed already existing directory " + dest + " ."))
    except:
        log(format%("Could not remove the already existing destination directory " + dest + " ."))
        return False
    try:
        shutil.copytree(source, dest)
        log(format%("Copied source directory " + source + " to " + dest + " ."))
    except:
        log(format%("Could not copy directory " + source + " to " + dest + " ."))
        return False
    return True

def generate_httpd_conf():
    """Generates /etc/httpd/conf.d/youtube_cache.conf for apache web server for serving videos."""
    conf_file = os.path.join(apache_conf_dir, 'youtube_cache.conf')
    youtube_cache_conf = """
#
# file : """ + conf_file + """
#
# Youtube Cache is a squid url rewriter to cache videos from various websites.
# Check http://cachevideos.com/ for more details.
#

# ------------------- Note This --------------------
# Don't forget to reload httpd and squid services if you change this file.

Alias /video_cache """ + base_dir +"""

<Directory """ + base_dir + """>
  Options +Indexes
  Order Allow,Deny
  #Comment the following line and uncomment the next for public use 
  #Deny from all
  Allow from all
</Directory>
    """

    try:
        file = open(conf_file, 'w')
        file.write(youtube_cache_conf)
        file.close()
        log(format%("Generated config file for Apache webserver in file " + config_file + " ."))
    except:
        log(format%("Could not write config file for apache web server to " + config_file + " ."))
        return False
    return True

def error(error_code):
    """Report error while updating/installing youtube_cache with proper error code."""
    help_message =  """
Usage: update-yc (as root/super user)
Update script can only be used if Youtube Cache is installed on your system.
Please see http://cachevideos.com/update-yc for more information or getting help.
    """
    update_error =  """
An error has occured while updating youtube_cache.
Please check /var/log/squid/youtube_cache.log for more details.
Please see http://cachevideos.com/update-yc for more information or getting help.
    """
    uid_error = """
You must be root to setup/install youtube_cache.
Please see http://cachevideos.com/update-yc for more information or getting help.
    """
    if error_code == UPDATE_ERROR:
        print update_error
        sys.exit(error_code)
    if error_code == UID_ERROR:
        print uid_error
        sys.exit(UID_ERROR)
    if error_code == USAGE_ERROR:
        print help_message
        sys.exit(USAGE_ERROR)
    return

def success():
    """Print informative messages after successfull installation."""
    message = """
Youtube cache update has completed successfully.
Now you must reload httpd service on your machine by using the following command
[root@localhost ~]# service httpd reload [ENTER]
In case of any bugs or problems, check http://cachevideos.com/ .
    """
    print message

def update():
    """Perform the update."""
    if not os.path.isdir(apache_conf_dir):
        if not create_dir(apache_conf_dir):
            error(UPDATE_ERROR)
    else:
        log(format%("Directory " + apache_conf_dir + " already exists."))

    if not os.path.isdir(squid_conf_dir):
        if not create_dir(squid_conf_dir):
            error(UPDATE_ERROR)
    else:
        log(format%("Directory " + squid_conf_dir + " already exists."))

    if not os.path.isdir(squid_log_dir):
        if not create_dir(squid_log_dir, squid_user, squid_group):
            error(UPDATE_ERROR)
    else:
        log(format%("Directory " + squid_log_dir + " already exists."))

    for dir in squid_cache_dir_list:
        if not os.path.isdir(dir):
            if not create_dir(dir, squid_user, squid_group):
                error(UPDATE_ERROR)
        else:
            if not dir_perms_and_ownership(dir, squid_user, squid_group):
                error(UPDATE_ERROR)
            log(format%("Directory " + dir + " already exists."))

    if not create_file(os.path.join(squid_log_dir, 'youtube_cache.log'), squid_user, squid_group):
        error(UPDATE_ERROR)

    if not generate_httpd_conf():
        error(UPDATE_ERROR)

    success()
    return

if __name__ == '__main__':
    log = set_logging()
    if os.getuid() != 0:
        log(format%("You must be root to install/setup youtube_cache."))
        error(UID_ERROR)
    else:
        update()
