.TH "YOUTUBE_CACHE" 1 "November 19, 2008" ""

.SH 1. NAME
.P
\fByoutube_cache\fR \- Squid url rewriter plugin to cache dynamic audio/video content from different video portals/websites.

.SH 2. SYNOPSIS
.P
To be used as a url rewriter plugin with squid.

.SH 3. DESCRIPTION
.P
\fByoutube_cache\fR is a squid url rewriter plugin written in Python to facilitate youtube, metacafe, dailymotion, google, vimeo, redtube, xtube, youporn and msn soapbox videos and wrzuta.pl audio caching. It can cache videos from various websites in a separate directory (other than squid cache) in a browsable fashion and can serve the subsequent requests from the cache. It helps in saving bandwidth and loading time of the videos.

.P
\fByoutube_cache\fR is currently used by many ISPs.

.SH 4. REQUIRES
.nf
  1. squid >= 2.6
  2. python >= 2.4
  3. python-iniparse
  4. python-urlgrabber
  5. Apache or any other Web Server
.fi


.SH 5. CONFIGURATION
.P
To configure youtube_cache, you need to configure Proxy Server (squid) and the global \fByoutube_cache\fR configuration file. Below are the steps to configure \fByoutube_cache\fR.

.SS 5.1. SQUID CONFIGURATION
.P
To configure squid to use youtube_cache as a url rewriter program, you need to add the following lines to your sqiud configuration file (generally found at \fI/etc/squid/squid.conf\fR )

.nf
  # --BEGIN-- youtube_cache config for squid
  acl youtube_query url_regex -i \e.youtube\e.com\e/get_video
  acl youtube_query url_regex -i \e.cache[a-z0-9]?[a-z0-9]?[a-z0-9]?\e.googlevideo\e.com\e/videoplayback
  acl youtube_query url_regex -i \e.cache[a-z0-9]?[a-z0-9]?[a-z0-9]?\e.googlevideo\e.com\e/get_video
  acl youtube_deny url_regex -i http:\e/\e/[a-z][a-z]\e.youtube\e.com
  acl metacafe_query dstdomain v.mccont.com
  acl dailymotion_query url_regex -i proxy\e-[0-9][0-9]\e.dailymotion\e.com\e/
  acl google_query dstdomain vp.video.google.com
  acl redtube_query dstdomain dl.redtube.com
  acl xtube_query url_regex -i [a-z0-9][0-9a-z][0-9a-z]?[0-9a-z]?[0-9a-z]?\e.xtube\e.com\e/(.*)flv
  acl vimeo_query url_regex -i bitcast\e.vimeo\e.com\e/vimeo\e/videos\e/
  acl wrzuta_query url_regex -i va\e.wrzuta\e.pl\e/wa[0-9][0-9][0-9][0-9]?
  acl youporn_query url_regex -i \e.files\e.youporn\e.com\e/(.*)\e/flv\e/
  acl soapbox_query url_regex -i \e.msn\e.com\e.edgesuite\e.net\e/(.*)\e.flv
  url_rewrite_access deny youtube_deny
  url_rewrite_access allow youtube_query
  url_rewrite_access allow metacafe_query
  url_rewrite_access allow dailymotion_query
  url_rewrite_access allow google_query
  url_rewrite_access allow redtube_query
  url_rewrite_access allow xtube_query
  url_rewrite_access allow vimeo_query
  url_rewrite_access allow wrzuta_query
  url_rewrite_access allow youporn_query
  url_rewrite_access allow soapbox_query
  redirector_bypass on
  # --END-- youtube_cache config for squid
.fi


.P
Now restart or reload the squid service using the command

.nf
  [root@localhost ~]# service squid reload [ENTER]
.fi

.P
OR

.nf
  [root@localhost ~]# service squid restart [ENTER]
.fi


.SS 5.2. YOUTUBE_CACHE GLOBAL CONFIGURATION
.P
\fBConfig file\fR : /etc/youtube_cache.conf

.TP
\fBbase_dir\fR
Base directory for caching the videos. All other directory paths should be relative to base_dir.
.nf
  Default : /var/spool/squid/video_cache/
.fi


.TP
\fBtemp_dir\fR
Directory to store partially downloaded videos. Directory name is relative to base_dir. e.g. if you specify temp_dir = tmp, actual path for storing partially downloaded videos would be /var/spool/squid/video_cache/tmp/ .
.nf
  Default : tmp
.fi


.TP
\fBmax_parallel_downloads\fR
The maximum number of parallel downloads allowed. If all connections are consumed, videos will be queued for download.
.nf
  Default : 30
.fi


.TP
\fBcache_host\fR
.nf
  The hostname or IP address of the system on which caching is being done. This is used for serving the videos from the cache.
  Please don’t use http:// or slashes (/). Just specify the domain name or IP address.
  Example : localhost.localdomain
  or proxy.example.com
  or 192.168.36.204
  or <Proxy_Server_IP_OR_Domain>
  Default : 127.0.0.1
.fi


.TP
\fBrpc_host\fR
XMLRPCServer is used for memory sharing across different instances of youtube_cache. Leave these settings as it is if you don’t have a fair idea of XMLRPCServer. This will be same as cache_host in almost all the cases.
.nf
  Default : 127.0.0.1
.fi


.TP
\fBrpc_port\fR
Please make sure this port is not currently in use. If it is in use by some other program, change this to some port above 1024 which is not in use by any other program.
.nf
  Default : 9100
.fi


.TP
\fBlogfile\fR
File where youtube cache log will be stored.
.nf
  Default : /var/log/squid/youtube_cache.log
.fi


.TP
\fBmax_logfile_size\fR
Maximum size of logfile specified above. The size is in mega bytes.
.nf
  Note : Please don’t use max_logfile_size = 10MB. Don’t append MB.
  Default : 10
.fi


.TP
\fBmax_logfile_backups\fR
The logfiles are automatically rotated once they have exceeded the max_logfile_size. max_logfile_backups is the number of backup files you want to keep.  e.g. max_logfile_backups = 2 will keep youtube_cache.log and youtube_cache.log.1 and youtube_cache.log.2 as logfiles.
.nf
  Default : 10
.fi


.TP
\fBproxy\fR
.nf
  Proxy for http content.
  Example : http_proxy = http://<Proxy_Server_IP_OR_Domain>:<Proxy_port>/
  or http://proxy.example.com:3128/
  Default : http://127.0.0.1:3128/
.fi


.TP
\fBproxy_username\fR
If the above proxy requires authentication, please specify the username.
.nf
  Default : <blank>
.fi


.TP
\fBproxy_password\fR
If the above proxy requires authentication, please specify the password.
.nf
  Default : <blank>
.fi


.TP
\fBenable_youtube_cache\fR
This option enables the caching of youtube videos. This option’s value can be either 0 or 1.
.nf
  Default : 1
.fi


.TP
\fByoutube_cache_dir\fR
Directory to cach youtube videos. Directory name is relative to base_dir. e.g. if you specify youtube_cache_dir = youtube, actual path for caching youtube videos would be /var/spool/squid/video_cache/youtube/ .
.nf
  Default : youtube
.fi


.TP
\fByoutube_cache_size\fR
Maximum total size of youtube caching directory. 0 for unlimited. This size is in Mega Bytes. e.g. youtube_cache_size = 200 will limit your cache size to 200MB.
.nf
  NOTE : Don’t use cache_size = 200MB. Don’t append MB.
  Default : 0
.fi


.TP
\fBmax_youtube_video_size\fR
Youtube videos with size more than max_youtube_video_size will not be cached. This size is in kilo bytes. Use 0 for unlimited caching. e.g. max_youtube_video_size = 10000. Only videos with size less than 10MB (10000KB) will be cached. 
.nf
  NOTE : Don’t use max_youtube_video_size = 10000KB. Don’t append KB.
  Default : 0
.fi


.TP
\fBmin_youtube_video_size\fR
Youtube videos with size less than min_youtube_video_size will not be cached. This size is in kilo bytes. Use 0 for no lower limit. e.g. min_youtube_video_size = 10. Only videos with size more than 10KB will be cached.
.nf
  NOTE : Don’t use min_youtube_video_size = 10KB. Don’t append KB.
  Default : 0
.fi


.TP
\fBenable_metacafe_cache\fR
See description for enable_youtube_cache.
.nf
  Default : 1
.fi


.TP
\fBmetacafe_cache_dir\fR
See description for youtube_cache_dir.
.nf
  Default : metacafe
.fi


.TP
\fBmetacafe_cache_size\fR
See description for youtube_cache_size.
.nf
  Default : 0
.fi


.TP
\fBmax_metacafe_video_size\fR
See description for max_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBmin_metacafe_video_size\fR
See description for min_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBenable_dailymotion_cache\fR
See description for enable_youtube_cache.
.nf
  Default : 1
.fi


.TP
\fBdailymotion_cache_dir\fR
See description for youtube_cache_dir.
.nf
  Default : dailymotion
.fi


.TP
\fBdailymotion_cache_size\fR
See description for youtube_cache_size.
.nf
  Default : 0
.fi


.TP
\fBmax_dailymotion_video_size\fR
See description for max_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBmin_dailymotion_video_size\fR
See description for min_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBenable_google_cache\fR
See description for enable_youtube_cache.
.nf
  Default : 1
.fi


.TP
\fBgoogle_cache_dir\fR
See description for youtube_cache_dir.
.nf
  Default : google
.fi


.TP
\fBgoogle_cache_size\fR
See description for youtube_cache_size.
.nf
  Default : 0
.fi


.TP
\fBmax_google_video_size\fR
See description for max_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBmin_google_video_size\fR
See description for min_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBenable_redtube_cache\fR
See description for enable_youtube_cache.
.nf
  Default : 1
.fi


.TP
\fBredtube_cache_dir\fR
See description for youtube_cache_dir.
.nf
  Default : redtube
.fi


.TP
\fBredtube_cache_size\fR
See description for youtube_cache_size.
.nf
  Default : 0
.fi


.TP
\fBmax_redtube_video_size\fR
See description for max_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBmin_redtube_video_size\fR
See description for min_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBenable_xtube_cache\fR
See description for enable_youtube_cache.
.nf
  Default : 1
.fi


.TP
\fBxtube_cache_dir\fR
See description for youtube_cache_dir.
.nf
  Default : xtube
.fi


.TP
\fBxtube_cache_size\fR
See description for youtube_cache_size.
.nf
  Default : 0
.fi


.TP
\fBmax_xtube_video_size\fR
See description for max_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBmin_xtube_video_size\fR
See description for min_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBenable_vimeo_cache\fR
See description for enable_youtube_cache.
.nf
  Default : 1
.fi


.TP
\fBvimeo_cache_dir\fR
See description for youtube_cache_dir.
.nf
  Default : vimeo
.fi


.TP
\fBvimeo_cache_size\fR
See description for youtube_cache_size.
.nf
  Default : 0
.fi


.TP
\fBmax_vimeo_video_size\fR
See description for max_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBmin_vimeo_video_size\fR
See description for min_youtube_video_size.
.nf
  Default : 0
.fi

.TP
\fBenable_wrzuta_cache\fR
See description for enable_youtube_cache.
.nf
  Default : 1
.fi


.TP
\fBwrzuta_cache_dir\fR
See description for youtube_cache_dir.
.nf
  Default : wrzuta
.fi


.TP
\fBwrzuta_cache_size\fR
See description for youtube_cache_size.
.nf
  Default : 0
.fi


.TP
\fBmax_wrzuta_video_size\fR
See description for max_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBmin_wrzuta_video_size\fR
See description for min_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBenable_youporn_cache\fR
See description for enable_youtube_cache.
.nf
  Default : 1
.fi


.TP
\fByouporn_cache_dir\fR
See description for youtube_cache_dir.
.nf
  Default : youporn
.fi


.TP
\fByouporn_cache_size\fR
See description for youtube_cache_size.
.nf
  Default : 0
.fi


.TP
\fBmax_youporn_video_size\fR
See description for max_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBmin_youporn_video_size\fR
See description for min_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBenable_soapbox_cache\fR
See description for enable_youtube_cache.
.nf
  Default : 1
.fi


.TP
\fBsoapbox_cache_dir\fR
See description for youtube_cache_dir.
.nf
  Default : soapbox
.fi


.TP
\fBsoapbox_cache_size\fR
See description for youtube_cache_size.
.nf
  Default : 0
.fi


.TP
\fBmax_soapbox_video_size\fR
See description for max_youtube_video_size.
.nf
  Default : 0
.fi


.TP
\fBmin_soapbox_video_size\fR
See description for min_youtube_video_size.
.nf
  Default : 0
.fi


.SH 6. FILES
.nf
  /etc/youtube_cache.conf
  /etc/httpd/conf.d/youtube_cache.conf
  /etc/squid/youtube_cache/
  /var/spool/squid/video_cache/
  /var/log/squid/youtube_cache.log
  /usr/sbin/update-yc
.fi


.SH 7. SEE ALSO
.P
\fIsquid (8)\fR

.nf
  Project Website : http://cachevideos.com/
  How to configure squid : http://fedora.co.in/content/how-configure-squid-proxy-server
  How to write custorm squid redirector in python : http://fedora.co.in/content/writing-custom-redirector-plugin-squid-python
.fi


.SH 8. AUTHOR
.P
Kulbir Saini <kulbirsaini AT students.iiit.ac.in>

.SH 9. BUGS, SUGGESTIONS, COMMENTS
.P
Please visit http://cachevideos.com/forum/ .


.\" man code generated by txt2tags 2.4 (http://txt2tags.sf.net)
.\" cmdline: txt2tags -t man -i youtube_cache.8.t2t -o youtube_cache.8

