#!/usr/bin/env python

#
# (C) Copyright 2008-2010 Kulbir Saini <saini@saini.co.in>
# (C) Copyright 2008-2010 Videocache Pvt Ltd.
#
# For more information check http://cachevideos.com/
#

__author__ = """Kulbir Saini <kulbirsaini@students.iiit.ac.in>"""
__docformat__ = 'plaintext'

CACHE_URL_ERR = 'CACHE_URL_ERR'
WEBSITE_OPTIONS_ERR = 'WEBSITE_OPTIONS_ERR'
CACHE_DIR_BUILD_ERR = 'CACHE_DIR_BUILD_ERR'
RPC_CONNECT_WARN = 'RPC_CONNECT_WARN'
RPC_CONNECT_ERR = 'RPC_CONNECT_ERR'
RPC_CONNECT = 'RPC_CONNECT'
VIDEOCACHE_START_ERR = 'VIDEOCACHE_START_ERR'
VIDEOCACHE_START_WARN = 'VIDEOCACHE_START_WARN'
VIDEOCACHE_START = 'VIDEOCACHE_START'
VIDEOCACHE_RUNTIME_ERR = 'VIDEOCACHE_RUNTIME_ERR'
INPUT_WARN = 'INPUT_WARN'
HTTP_METHOD_WARN = 'HTTP_METHOD_WARN'
URL_WARN = 'URL_WARN'
INPUT_PARSE_ERR = 'INPUT_PARSE_ERR'
URL_ERR = 'URL_ERR'
URL_HIT = 'URL_HIT'
CACHE_MISS = 'CACHE_MISS'
CACHE_HIT = 'CACHE_HIT'
WRITEBACK_ERR = 'WRITEBACK_ERR'
VIDEOCACHE_EXIT = 'VIDEOCACHE_EXIT'
LOCAL_POOL_LOCK_ERR = 'LOCAL_POOL_LOCK_ERR'
FORK_1_FAILED = 'FORK_1_FAILED'
FORK_2_FAILED = 'FORK_2_FAILED'
PID_NOT_FOUND = 'PID_NOT_FOUND'
VIDEO_POOL_SERVER_START = 'VIDEO_POOL_SERVER_START'
VIDEO_POOL_SERVER_START_ERR = 'VIDEO_POOL_SERVER_START_ERR'
VIDEO_SUBMIT = 'VIDEO_SUBMIT'
VIDEO_SUBMIT_ERR = 'VIDEO_SUBMIT_ERR'
VIDEO_SUBMIT_FAIL = 'VIDEO_SUBMIT_FAIL'
VIDEO_SUBMIT_WARN = 'VIDEO_SUBMIT_WARN'
VIDEO_SYNC_START = 'VIDEO_SYNC_START'
VIDEO_SYNC_STOP = 'VIDEO_SYNC_STOP'
VIDEOS_RECEIVED = 'VIDEOS_RECEIVED'
