#!/usr/bin/env python
#
# (C) Copyright 2008-2011 Kulbir Saini <saini@saini.co.in>
#
# For more information check http://cachevideos.com/
#

__author__ = """Kulbir Saini <saini@saini.co.in>"""
__docformat__ = 'plaintext'

from optparse import OptionParser

import os
import sys

if __name__ == '__main__':
    # Parse command line options.
    parser = OptionParser()
    parser.add_option('-p', '--prefix', dest = 'vc_root', type='string', help = 'Specify an alternate root location for videocache', default = '/')
    parser.add_option('-c', '--config', dest = 'config_file', type='string', help = 'Use an alternate configuration file', default = '/etc/videocache.conf')
    parser.add_option('-a', '--apache-dir', dest = 'apache_dir', type='string', help = 'Path to conf.d directory for Apache. Default is /etc/apache2/conf.d/', default = '/etc/apache2/conf.d/')
    options, args = parser.parse_args()

    if options.vc_root[0] != '/':
        root = os.path.join(os.getcwd(), options.vc_root)
    else:
        root = options.vc_root

    install_dir = os.path.join(root, 'usr/share/videocache/')
    # Try to locate the videocache directory containing python files.
    if os.path.isdir(install_dir):
        sys.path = [install_dir] + sys.path
        from vcoptions import VideocacheOptions
        from common import *
    elif os.path.isdir('/usr/share/videocache/'):
        install_dir = '/usr/share/videocache/'
        sys.path = [install_dir] + sys.path
        from vcoptions import VideocacheOptions
        from common import *
    else:
        help_message =  """
Usage: vc-update -h (as root/super user)
Update script can only be used if Videocache is installed on your system.
Please see http://cachevideos.com/vc-update for more information or getting help.
        """
        sys.stderr.write(help_message + '\n')
        parser.print_help()
        sys.exit(1)

    if os.getuid() != 0:
        parser.print_help()
        update_error('uid')

    try:
        o = VideocacheOptions(options.config_file, root)
    except Exception, e:
        message = 'vc-update: Could not read options from configuration file.'
        sys.stderr.write(message + '\n')
        syslog_msg(message)
        parser.print_help()
        sys.exit(1)

    if o.halt:
        message = 'vc-updaet: One or more errors occured in reading configure file. Please check syslog messages generally located at /var/log/messages.'
        sys.stderr.write(message + '\n')
        syslog_msg(message)
        parser.print_help()
        sys.exit(1)

    update_vc(o, root, install_dir, options.apache_dir)

