#!/usr/bin/env python
#
# (C) Copyright 2008-2011 Kulbir Saini <saini@saini.co.in>
#
# For more information check http://cachevideos.com/
#

__author__ = """Kulbir Saini <saini@saini.co.in>"""
__docformat__ = 'plaintext'

from optparse import OptionParser

import os
import sys
import traceback

if __name__ == '__main__':
    # Parse command line options.
    parser = OptionParser()
    parser.add_option('-v', '--verbose', dest = 'verbose', action='store_true', help = 'Print detailed log messages.', default = False)
    parser.add_option('-p', '--prefix', dest = 'vc_root', type='string', help = 'Specify an alternate root location for videocache', default = '/')
    parser.add_option('-c', '--config', dest = 'config_file', type='string', help = 'Use an alternate configuration file', default = '/etc/videocache.conf')
    parser.add_option('-u', '--squid-user', dest = 'squid_user', type='string', help = 'User who runs Squid daemon.')
    parser.add_option('-a', '--apache-dir', dest = 'apache_dir', type='string', help = 'Path to conf.d directory for Apache. In most cases, it\'ll be /etc/httpd/conf.d/ or /etc/apache2/conf.d/.')
    parser.add_option('-s', '--skip-apache-conf', dest = 'skip_apache_conf', action='store_true', help = 'Skip creating Videocache specific configuration for Apache.', default = False)
    options, args = parser.parse_args()

    help_message =  """
Usage: vc-update -h (as root/super user)
Update script can only be used if Videocache is installed on your system.
Please see http://cachevideos.com/vc-update for more information or getting help.
"""

    uid_error = """
You must be root to update Videocache installation.
Please see http://cachevideos.com/vc-update for more information or getting help.
"""

    if os.getuid() != 0:
        parser.print_help()
        sys.stderr.write(uid_error)
        sys.exit(1)

    if options.skip_apache_conf:
        apache_dir = None
    elif options.apache_dir == None or options.apache_dir == '':
        httpd_dir = os.path.join(options.vc_root, 'etc/httpd/conf.d/')
        apache2_dir = os.path.join(options.vc_root, 'etc/apache2/conf.d/')
        if os.path.isdir(httpd_dir):
            apache_dir = httpd_dir
        elif os.path.isdir(apache2_dir):
            apache_dir = apache2_dir
        else:
            parser.print_help()
            sys.stderr.write('\nPlease use -a (or --apache-dir) option to specify the path to Apache\'s conf.d directory.\n')
            sys.exit(1)
    else:
        apache_dir = options.apache_dir

    if options.vc_root[0] != '/':
        root = os.path.join(os.getcwd(), options.vc_root)
    else:
        root = options.vc_root

    install_dir = os.path.join(root, 'usr/share/videocache/')
    # Try to locate the videocache directory containing python files.
    if os.path.isdir(install_dir):
        sys.path = [install_dir] + sys.path
        from vcoptions import VideocacheOptions
        from common import *
    elif os.path.isdir('/usr/share/videocache/'):
        install_dir = '/usr/share/videocache/'
        sys.path = [install_dir] + sys.path
        from vcoptions import VideocacheOptions
        from common import *
    else:
        sys.stderr.write(help_message)
        parser.print_help()
        sys.exit(1)

    try:
        o = VideocacheOptions(options.config_file, root)
    except Exception, e:
        message = 'vc-update: Could not read options from configuration file.\n'
        sys.stderr.write(message)
        syslog_msg(message)
        parser.print_help()
        log_traceback()
        sys.exit(1)

    if o.halt:
        message = 'vc-update: One or more errors occured in reading configure file. Please check syslog messages generally located at /var/log/messages.\n'
        sys.stderr.write(message)
        syslog_msg(message)
        parser.print_help()
        sys.exit(1)

    squid_user = options.squid_user or o.videocache_user
    update_vc(o, root, squid_user, install_dir, apache_dir, not options.verbose)

